'use client';

import Link from 'next/link';
import { useCallback, useEffect, useState } from 'react';
import { ArrowRight, Printer, Save } from 'lucide-react';
import { Footer, Header } from './investlab';
import PeriodStudyPrintReport from './period-study-print-report';
import { loadPeriodStudyById, PERIOD_STUDY_CHANGED_EVENT, updatePeriodStudy, type PeriodSnapshot, type PeriodStudyRecord } from '@/lib/period-study-storage';

const number = new Intl.NumberFormat('ko-KR', { maximumFractionDigits: 2 });
const signed = (value: number, suffix = '') => `${value > 0 ? '+' : ''}${number.format(Object.is(value, -0) ? 0 : value)}${suffix}`;
const metrics = (item: PeriodSnapshot) => [['시작 예시 가격', number.format(item.startPrice)], ['종료 예시 가격', number.format(item.endPrice)], ['변화액', signed(item.priceChange)], ['변화율', signed(item.changeRate, '%')], ['최고 예시 가격', number.format(item.highestPrice)], ['최저 예시 가격', number.format(item.lowestPrice)], ['변동폭', number.format(item.range)], ['포인트 수', `${item.pointCount}개`]];

export default function PeriodStudyDetail({ id }: { id: string }) {
  const [item, setItem] = useState<PeriodStudyRecord | null>(null);
  const [ready, setReady] = useState(false);
  const [hypothesis, setHypothesis] = useState('');
  const [reflection, setReflection] = useState('');
  const [notice, setNotice] = useState('');
  const [error, setError] = useState('');
  const refresh = useCallback(() => { const next = loadPeriodStudyById(id); setItem(next); if (next) { setHypothesis(next.hypothesis); setReflection(next.reflection); } setReady(true); }, [id]);
  useEffect(() => { refresh(); window.addEventListener('storage', refresh); window.addEventListener(PERIOD_STUDY_CHANGED_EVENT, refresh); return () => { window.removeEventListener('storage', refresh); window.removeEventListener(PERIOD_STUDY_CHANGED_EVENT, refresh); }; }, [refresh]);
  const saveMetadata = () => { try { const updated = updatePeriodStudy(id, hypothesis, reflection); setItem(updated); setNotice('학습 가설과 메모를 수정했습니다.'); setError(''); } catch (reason) { setError(reason instanceof Error ? reason.message : '학습 기록을 수정하지 못했어요.'); } };
  if (!ready) return <><Header /><main className="simulation-page"><section className="container saved-loading" role="status"><span />학습 기록을 불러오는 중이에요.</section></main><Footer /></>;
  if (!item) return <><Header /><main className="simulation-page"><section className="container simulation-empty"><strong>학습 기록을 찾을 수 없습니다.</strong><p>기록이 삭제되었거나 올바르지 않은 주소입니다.</p><div className="simulation-actions"><Link href="/studies" className="primary-button">학습 기록 목록</Link><Link href="/assets/TSLA" className="secondary-button">기간 비교 시작</Link></div></section></main><Footer /></>;
  const summary = `Period A 변화율은 ${signed(item.analysisA.changeRate, '%')}, Period B는 ${signed(item.analysisB.changeRate, '%')}이며 두 구간의 변화율 차이는 ${number.format(item.differences.changeRateDifference)}%p입니다.`;
  return <><Header /><main className="study-detail-page report-page"><section className="container history-heading"><span className="eyebrow">저장된 교육용 학습 기록</span><h1>{item.assetName} 기간 비교</h1><p>이 기록은 저장 당시의 교육용 예시 데이터와 계산 결과를 보존합니다.</p><button type="button" className="primary-button print-button print-hidden" onClick={() => window.print()}><Printer size={16} /> 학습 리포트 인쇄 / PDF 저장</button></section><section className="container study-summary"><strong>구간 비교 요약</strong><p>{summary}</p><time dateTime={item.createdAt}>저장 시각 {new Date(item.createdAt).toLocaleString('ko-KR')}</time></section><section className="container study-edit-card"><label htmlFor="study-detail-hypothesis">이번 비교에서 확인하고 싶은 것</label><textarea id="study-detail-hypothesis" maxLength={200} value={hypothesis} onChange={(event) => setHypothesis(event.target.value)} /><small>{hypothesis.length} / 200</small><label htmlFor="study-detail-reflection">학습 메모</label><textarea id="study-detail-reflection" maxLength={500} value={reflection} onChange={(event) => setReflection(event.target.value)} /><small>{reflection.length} / 500</small>{notice && <p className="storage-notice" role="status">{notice}</p>}{error && <p className="storage-error" role="alert">{error}</p>}<button type="button" className="primary-button" onClick={saveMetadata}><Save size={16} /> 가설과 메모 수정</button></section><section className="container period-metrics-grid study-snapshot-grid">{([['Period A', item.periodA, item.analysisA], ['Period B', item.periodB, item.analysisB]] as const).map(([label, range, analysis]) => <article className="period-result-card" key={label}><span className="compare-label">{label}</span><p className="period-range-summary">포인트 {range.startIndex + 1} ~ {range.endIndex + 1}</p><dl>{metrics(analysis).map(([name, value]) => <div key={name}><dt>{name}</dt><dd>{value}</dd></div>)}</dl></article>)}</section><section className="container period-difference"><div><span>변화액 차이</span><strong>{number.format(item.differences.priceChangeDifference)}</strong></div><div><span>변화율 차이</span><strong>{number.format(item.differences.changeRateDifference)}%p</strong></div><div><span>최고값 차이</span><strong>{number.format(item.differences.highestPriceDifference)}</strong></div><div><span>최저값 차이</span><strong>{number.format(item.differences.lowestPriceDifference)}</strong></div><div><span>변동폭 차이</span><strong>{number.format(item.differences.rangeDifference)}</strong></div><div><span>포인트 수 차이</span><strong>{item.differences.pointCountDifference}개</strong></div></section><section className="container education-warning"><strong>교육용 기록 안내</strong><p>이 기록은 예시 데이터 구간을 관찰한 학습 자료이며 실제 시세, 미래 시장 전망 또는 투자 판단을 의미하지 않습니다.</p></section><div className="container period-actions"><Link href={`/assets/${encodeURIComponent(item.assetSymbol)}`} className="primary-button">이 범위 다시 보기 <ArrowRight size={16} /></Link><Link href="/studies" className="secondary-button">학습 기록 목록</Link></div><PeriodStudyPrintReport record={item} /></main><Footer /></>;
}
